# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.ssh.insert_key = false
  config.vbguest.auto_update = true
  config.vm.box_check_update = false

  # create Management (mgmt) node
  config.vm.define "mgmt" do |mgmt_config|
    mgmt_config.vm.box = "ubuntu/trusty64"
    mgmt_config.vm.hostname = "mgmt"
    mgmt_config.vm.network "private_network", ip: "192.168.56.10"
    mgmt_config.vm.provider "virtualbox" do |vb|
      vb.name = "mgmt"
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.memory = "512"
    end # of vb
    # Shared folders
    if Vagrant::Util::Platform.windows? then
      # Configuration SPECIFIC for Windows 10 hosts
      mgmt_config.vm.synced_folder "examples", "/home/vagrant/examples",
      id: "vagrant-root", ouner: "vagrant", group: "vagrant",
      mount_options: ["dmode=775", "fmode=664"]
    else
      # Configuration for Unix/Linux hosts
      mgmt_config.vm.synced_folder "examples", "/home/vagrant/examples",
      mount_options: ["dmode=775", "fmode=664"]
    end # of shared folders
    # Provisioning
    mgmt_config.vm.provision "shell", path: "bootstrap-mgmt.sh"
  end # of mgmt_config

  # create Load Balancer node
  config.vm.define "balancer" do |lbal_config|
    lbal_config.vm.box = "ubuntu/trusty64"
    lbal_config.vm.hostname = "balancer"
    lbal_config.vm.network "private_network", ip: "192.168.56.11"
    lbal_config.vm.network "forwarded_port", guest: 80, host: 8080
    lbal_config.vm.provider "virtualbox" do |vb|
      vb.name = "balancer"
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.memory = "256"
    end # of vb
  end # of lbal_config

  # create some web servers
  # https://docs.vagrantup.com/v2/vagrantfile/tips.html
  (1..6).each do |i|
    config.vm.define "web#{i}" do |node|
      node.vm.box = "ubuntu/trusty64"
      node.vm.hostname = "web#{i}"
      node.vm.network "private_network", ip: "192.168.56.#{20+i}"
      node.vm.network "forwarded_port", guest: 80, host: 8080+i
      node.vm.provider "virtualbox" do |vb|
        vb.name = "web#{i}"
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        vb.memory = "256"
      end # of vb
    end # of node
  end # of loop
end # of config
